mobile_base_controller:
  type: "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['front_left_wheel_joint', 'front_right_wheel_joint']
  rear_wheel: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
  front_steering: ['front_left_steer_joint', 'front_right_steer_joint']
  rear_steering: ['rear_left_steer_joint', 'rear_right_steer_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 25.0 # not tested here

  # Base frame_id
  base_frame_id: base_footprint

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true
